bispenv/Django-CRM-master/crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('marketing/', include('marketing.urls', namespace="marketing")),
    path('myapp/', include('myapp.urls', namespace="myapp")),

    path('Leadanalytics/', include('LeadApplication.urls')),


    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

bispenv/Django-CRM-master/marketingold/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import (
    dashboard, contact_lists, contacts_list, contact_list_new, contacts_list_new, contact_list_detail, edit_contact,

    edit_contact_list, delete_contact_list, failed_contact_list_detail, failed_contact_list_download_delete,
  demo_file_download, delete_contact,  contact_detail,
    edit_failed_contact, delete_failed_contact,func_chat_detail,fun_calendar,fun_add_event,fun_remove,fun_update,BasicUploadView,clear_database,
link_contacts_list,link_contact_detail, func_link_chat_detail, fun_export_users_xls,fun_read_pdf,event_list_detail
)

app_name = 'marketing'

urlpatterns = [
    path('', dashboard, name='dashboard'),

    path('contact-list/', contact_lists, name='contact_lists'),
    path('contacts/<int:pk>/edit/', edit_contact, name='edit_contact'),
    path('contacts/<int:pk>/delete/', delete_contact, name='delete_contact'),

    path('contacts/', contacts_list, name='contacts_list'),
    path('contact-list/create/', contact_list_new, name='contact_list_new'),
    path('cl/list/cnew/', contacts_list_new, name='contacts_list_new'),
    path('contact-list/<int:pk>/detail/', contact_list_detail, name='contact_list_detail'),
    path('contact-list/<int:pk>/failed/', failed_contact_list_detail, name='failed_contact_list_detail'),
    path('contact-list/<int:pk>/failed/edit/', edit_failed_contact, name='edit_failed_contact'),
    path('contact-list/<int:pk>/failed/delete/', delete_failed_contact, name='delete_failed_contact'),
    path('contact-list/<int:pk>/failed/download/',
         failed_contact_list_download_delete, name='failed_contact_list_download_delete'),
    path('contact-list/<int:pk>/edit/', edit_contact_list, name='edit_contact_list'),
    path('contact-list/<int:pk>/delete/', delete_contact_list, name='delete_contact_list'),


    path('demo-file-download-for-contacts-list/', demo_file_download, name='demo_file_download'),

    path('contacts/<int:contact_id>/view/', contact_detail, name="contact_detail"),
    path('contacts/<str:user_id>/chatdetail/', func_chat_detail, name="func_chat_detail"),
    path('contacts/calendar/', fun_calendar, name='calendar'),
    path('contacts/add_event/', fun_add_event, name='fun_add_event'),
    path('contacts/update/', fun_update, name='fun_update'),
    path('contacts/remove/', fun_remove, name='fun_remove'),


    url(r'^basic-upload/$', BasicUploadView.as_view(), name='basic_upload'),
    url(r'^clear/$', clear_database, name='clear_database'),
    url(r'^pdf/$', fun_read_pdf, name='fun_read_pdf'),
    path('linkcontacts/', link_contacts_list, name='linkcontacts_list'),
    path('linkcontacts/<int:contact_id>/view/', link_contact_detail, name="link_contact_detail"),
    path('linkcontacts/<str:user_id>/chatdetail/',  func_link_chat_detail, name="func_link_chat_detail"),
    url(r'^export/xls/$', fun_export_users_xls, name='export_users_xls'),


    path('event-list/<int:pk>/detail/', event_list_detail, name='event_list_detail'),

]

bispenv/Django-CRM-master/marketingold/models.py
from datetime import datetime, timedelta
from django.db import models
from django.utils.timesince import timesince
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator
from common.models import User


class Pdf(models.Model):
    title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to='contacts/pdfs/')
    uploaded_at = models.DateTimeField(auto_now_add=True)


class Contactlinkedin(models.Model):

    name = models.CharField(max_length=500)
    email = models.EmailField()
    contact_number = models.CharField(
      max_length=20, blank=True, null=True)

    company_name = models.CharField(max_length=500, null=True, blank=True)
    last_name = models.CharField(max_length=500, null=True, blank=True)
    city = models.CharField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=500, null=True, blank=True)
    country = models.CharField(max_length=500, null=True, blank=True)
    skills = models.CharField(max_length=500, null=True, blank=True)
    language=models.CharField(max_length=500, null=True, blank=True)
    certification =models.CharField(max_length=500, null=True, blank=True)


    position = models.CharField(max_length=500, null=True, blank=True)


    def __str__(self):
        return self.email

    class Meta:
        ordering = ['id', ]

class Tag(models.Model):
    name = models.CharField(max_length=500)
    color = models.CharField(max_length=20,
                             default="#999999", verbose_name=_("color"))
    created_by = models.ForeignKey(User,
                                   related_name="marketing_tags",
                                   null=True, on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)

    @property
    def created_by_user(self):
        return self.created_by if self.created_by else None

class ContactList(models.Model):
    created_by = models.ForeignKey(
        User, related_name="marketing_contactlist",
        null=True, on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=500)
    tags = models.ManyToManyField(Tag)
    visible_to = models.ManyToManyField(User, related_name="contact_lists_visible_to")

    class Meta:
        ordering = ('id',)

    @property
    def created_by_user(self):
        return self.created_by if self.created_by else None

    @property
    def created_on_format(self):
        return self.created_on.strftime('%b %d, %Y %I:%M %p')

    @property
    def created_on_since(self):
        now = datetime.now()
        difference = now.replace(tzinfo=None) - \
            self.created_on.replace(tzinfo=None)

        if difference <= timedelta(minutes=1):
            return 'just now'
        return '%(time)s ago' % {
            'time': timesince(self.created_on).split(', ')[0]}

    @property
    def tags_data(self):
        return self.tags.all()

    @property
    def no_of_contacts(self):
        return self.contacts.all().count()

    @property
    def no_of_campaigns(self):
        return self.campaigns.all().count()

    @property
    def unsubscribe_contacts(self):
        return self.contacts.filter(is_unsubscribed=True).count()

    @property
    def bounced_contacts(self):
        return self.contacts.filter(is_bounced=True).count()

class Contact(models.Model):
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'. \
        Up to 20 digits allowed."
    )
    created_by = models.ForeignKey(
        User, related_name="marketing_contacts_created_by",
        null=True, on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    date = models.DateTimeField(auto_now=True)
    contact_list = models.ManyToManyField(ContactList, related_name="contacts")
    name = models.CharField(max_length=500)
    email = models.EmailField()
    contact_number = models.CharField(
      max_length=20, blank=True, null=True)
    is_unsubscribed = models.BooleanField(default=False)
    is_bounced = models.BooleanField(default=False)
    company_name = models.CharField(max_length=500, null=True, blank=True)
    last_name = models.CharField(max_length=500, null=True, blank=True)
    city = models.CharField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=500, null=True, blank=True)
    country = models.CharField(max_length=500, null=True, blank=True)
    Course = models.CharField(max_length=500, null=True, blank=True)
    Lead_Source = models.CharField(max_length=500, null=True, blank=True)
    position = models.CharField(max_length=500, null=True, blank=True)
    pdf_file = models.FileField(upload_to='contacts/pdfs/',null=True,blank=True)

    def __str__(self):
        return self.email

    class Meta:
        ordering = ['id', ]

class Message(models.Model):
     sender = models.ForeignKey(User, related_name="sender",on_delete=models.CASCADE)
     reciever = models.ForeignKey(User, related_name="reciever",on_delete=models.CASCADE)
     linkedin_contact = models.ForeignKey(Contact, related_name="linkedin",on_delete=models.CASCADE,default=8)
     msg_content =models.TextField()
     created_at = models.DateTimeField(auto_now_add=True)
     schedule_date_time = models.DateTimeField(blank=True, null=True)


class linkMessage(models.Model):
    sender = models.ForeignKey(User, related_name="linksender", on_delete=models.CASCADE)
    reciever = models.ForeignKey(User, related_name="linkreciever", on_delete=models.CASCADE)
    linkedin_contact = models.ForeignKey(Contactlinkedin, related_name="contactlinkedin", on_delete=models.CASCADE)
    msg_content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    schedule_date_time = models.DateTimeField(blank=True, null=True)

from django.urls import reverse

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    user = models.ForeignKey(User, related_name="user", on_delete=models.CASCADE,default=1)

    @property
    def get_html_url(self):
        url = reverse('marketing:event_details', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

class FailedContact(models.Model):
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'.\
        Up to 20 digits allowed."
    )
    created_by = models.ForeignKey(
        User, related_name="marketing_failed_contacts_created_by", null=True,
        on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)
    contact_list = models.ManyToManyField(
        ContactList, related_name="failed_contacts")
    name = models.CharField(max_length=500, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    contact_number = models.CharField(
        validators=[phone_regex], max_length=20, blank=True, null=True)
    company_name = models.CharField(max_length=500, null=True, blank=True)
    last_name = models.CharField(max_length=500, null=True, blank=True)
    city = models.CharField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=500, null=True, blank=True)
    contry = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.email

bispenv/Django-CRM-master/templates/marketingold/linkedinlist/all.html
{% extends 'marketing/base.html' %}
{% load staticfiles %}
{% load sorting_tags %}
{% load paginate %}
{% block content %}
{{ block.super }}

{% block extralinks %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
  <link rel="icon" type="image/png" href="{%static 'images/favicon.ico'%}"/>
{% endblock extralinks %}

<div class="main_container ml-5 mr-5">
  <div class="row marl">

    <div class="filter_row list_filter_row row marl col-md-12 mb-2">
      <div class="">
        <div class="card">
          <div class="card-body">
            <form id="leads_filter" action="" method="POST">
              <div class="card-body ">
                <div class="card-title">Filters</div>
                <div class="row marl">
                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Name</label>
                      <input type="text" class="form-control" placeholder="Contact Name" name="contact_name"
                        value="{{request.POST.contact_name}}">
                    </div>
                  </div>

                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Position</label>
                      <input type="text" class="form-control" placeholder="Position" name="contact_position"
                        value="{{request.POST.contact_position}}">
                    </div>
                  </div>


                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Email</label>
                      <input type="text" class="form-control" placeholder="Contact Email" name="contact_email"
                        value="{{request.POST.contact_email}}">
                    </div>
                  </div>

                   <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Company Name</label>
                      <input type="text" class="form-control" placeholder="Company Name" name="contact_company"
                        value="{{request.POST.contact_company}}">
                    </div>
                  </div>

                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Country</label>
                      <input type="text" class="form-control" placeholder="Country" name="country"
                        value="{{request.POST.country}}">
                    </div>
                  </div>

                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Skills</label>
                      <input type="text" class="form-control" placeholder="Skills" name="skills"
                        value="{{request.POST.skills}}">
                    </div>
                  </div>

                  <input type="hidden" name="tab_status" id="tab_status">
                  <div class="filter_col col-2">
                    <div class="form-group buttons_row">
                      <button class="btn btn-primary save" type="submit">Search</button>
                      <a href="" class="btn btn-default clear" onclick="window.location.reload">Clear</a>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="table_container_row no_mar_top">
        <div class="card">
          <div class="card-body">
            <div class="card-title text-right">
              <span class="float-left">Contacts - {{ contacts|length }}</span>
              <span class="filter_toggle">
                <a href="#" class="primary_btn"><i class="fas fa-filter"></i></a>
              </span>
              <a href="{% url 'marketing:basic_upload' %}" class="primary_btn">Upload New Pdf</a>
              <a href="{% url 'marketing:export_users_xls' %}" class="primary_btn" >Export all Contacts</a>
            </div>
            <div class="table-responsive table-bordered">
               {% autosort contacts %}
              <table class="table">
                {% if contacts %}

                <thead>
                  <tr>
                    <th width="5%">S. No</th>
                    <th width="15%">{% anchor name _("Full Name") %}</th>
                    <th width="10%">Email</th>
                    <th width="15%">Position</th>
                    <th width="15%">{% anchor company_name _("Company Name") %}</th>
                    <th width="15%">Certification</th>
                      <th width="15%">Language</th>
                      <th width="15%">Skills</th>
                        <th width="15%">Country</th>

                  </tr>
                </thead>
                {% endif %}
                <tbody>
                  {% if per_page %}
                  {% paginate per_page contacts %}
                  {% else%}
                  {% paginate 10 contacts %}
                  {% endif %}

                  {% for contact in contacts %}
                  <tr style="text-align:center;">
                    <td scope="row">{{ forloop.counter }}</td>
                    <td><a href="{% url 'marketing:link_contact_detail' contact.id %}">{{ contact.name }}</td>
                    <td class="text-center">{{ contact.email }}</td>
                      <td class="text-center">{{ contact.position }}</td>
                      <td class="text-center">{{ contact.company_name  }}</td>
                      <td class="text-center">{{ contact.certification }}</td>
                      <td class="text-center">{{ contact.language }}</td>
                      <td class="text-center">{{ contact.skills}}</td>
                      <td class="text-center">{{ contact.country }}</td>


                    <td>
                      {% for contact_list in contact.all %}
                      <span> <a
                          href="{% url 'marketing:link_contact_detail' contact_list.id %}">{{contact_list.name}}</a>
                      </span>
                      {% endfor %}
                    </td>

                  </tr>
                  {% empty %}
                  <tr style="text-align:center;">
                    <td colspan="6">No records found!</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="marl row text-center mt-5">
        {% show_pages %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js_block %}
<script>
  $(function () {
    $(".filter_toggle").click(function () {
      $(".list_filter_row").toggle();
    });
    $('#id_tag').select2();

    $("a[rel='page']").click(function (e) {
      e.preventDefault();
      $('#leads_filter').attr("action", $(this).attr("href"));
      $('#leads_filter').submit();
    });

    $(".remove_account").click(function (e) {
      e.preventDefault()
      url = $(this).attr('href')
      var contact_lists = parseInt($(this).attr('data-other-contacts-lists'));
      if (contact_lists > 1) {
        if (!confirm('Are you sure you want to delete? this contact exists in other contact lists, deleting this will delete this contact from other contact lists too!'))
          return;
        window.location = $(this).attr('href');
      } else {
        if (!confirm('Are you sure you want to delete?'))
          return;
        window.location = $(this).attr('href');
      }
    })

    $(".edit_contact").click(function (e) {
      e.preventDefault()
      url = $(this).attr('href')
      console.log(url)
      var contact_lists = parseInt($(this).attr('data-other-contacts-lists'));
      console.log(contact_lists);
      if (contact_lists > 1) {
        if (!confirm('Are you sure you want to edit? this contact exists in other contact lists, editing this will change this contact information in other contact lists too!'))
          return;
        window.location = $(this).attr('href');
      } else {
        window.location = $(this).attr('href');
      }
    })
  })
</script>
{% endblock js_block %}

bispenv/Django-CRM-master/templates/marketingold/linkedinlist/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bispenv/Django-CRM-master/templates/marketingold/linkedinlist/chat.html
{% extends 'marketing/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% load compress %}
{% block content %}
{{ block.super }}


<!------ Include the above in your HEAD tag ---------->




<!------ Include the above in your HEAD tag ---------->


<html>
<head>

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet">
{% load sass_tags %}
    <link href="{% sass_src 'E:/analytyics_leads_opportunity_pdf/bispenv/Django-CRM-master/static/css/chat.scss' %}" rel="stylesheet">
</head>
<body>
<form method="post">
<div class="container">
<h3 class="text-center">Stay connect with your colleagues</h3>
<div class="messaging">
      <div class="inbox_msg">
        <div class="inbox_people">
          <div class="headind_srch">
            <div class="recent_heading">
              <h4>Contacts</h4>
            </div>

          </div>
          <div class="inbox_chat">
            <div class="chat_list active_chat">
              <div class="chat_people">
             {% for user in user_role %}
                       {% if request.user.email != user.email %}
                           <div class="chat_img">
                                {% if user.profile_pic %}
                                    {% thumbnail user.profile_pic "125x125" as im %}
                                        <img src="{{ im.url }}">
                                    {% endthumbnail %}
                               {% endif %}
                            </div>
                           <div class="chat_ib">
                              <h5><a href="{% url 'marketing:func_link_chat_detail' user.id %}">{{user.username}}</a><span class="chat_date"></span></h5>
                               <p></p>
                           </div>
                       {% else %}
                      {% endif %}
                  {% endfor %}






                <div class="chat_ib">

                </div>
              </div>
            </div>






          </div>
        </div>
        <div class="mesgs">


    <img src="{% static 'images//peoples.jpg' %}" alt="Peoples"/>
</div>

          <div class="type_msg">
            <div class="input_msg_write">

            </div>
          </div>
        </div>
      </div>




    </div>
  </form>
    </body>

    </html>
</html>
{% endblock %}

bispenv/Django-CRM-master/templates/marketingold/linkedinlist/userchat.html
{% extends 'marketing/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% load compress %}
{% block content %}
{{ block.super }}


<!------ Include the above in your HEAD tag ---------->




<!------ Include the above in your HEAD tag ---------->


<html>
<head>

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet">
{% load sass_tags %}
    <link href="{% sass_src 'E:/analytyics_leads_opportunity_pdf/bispenv/Django-CRM-master/static/css/chat.scss' %}" rel="stylesheet">
</head>
<body>
<form method="post">
<div class="container">

<h3 class=" text-center">{{session_linkedin1.name}}-{{user_obj.username}}</h3>

<div class="messaging">
      <div class="inbox_msg">
        <div class="inbox_people">
          <div class="headind_srch">
            <div class="recent_heading">
              <h4>Contacts</h4>
            </div>

          </div>
          <div class="inbox_chat">
            <div class="chat_list active_chat">
              <div class="chat_people">
                 {% for user in user_role %}
                       {% if request.user.email != user.email %}
                           <div class="chat_img">
                                {% if user.profile_pic %}
                                    {% thumbnail user.profile_pic "125x125" as im %}
                                        <img src="{{ im.url }}">
                                    {% endthumbnail %}
                               {% endif %}
                            </div>
                           <div class="chat_ib">

                              <h5><a href="{% url 'marketing:func_link_chat_detail' user.id %}">{{user.username}}</a><span class="chat_date"></span></h5>
                               <p></p>


                           </div>
                       {% else %}

                      {% endif %}

                  {% endfor %}







                <div class="chat_ib">

                </div>
              </div>
            </div>


          </div>
        </div>
        <div class="mesgs">
          <div class="msg_history">
            <div class="incoming_msg">

              <div class="incoming_msg_img">

                     {% if user_obj.profile_pic %}

                        {% thumbnail user_obj.profile_pic "125x125" as im %}
                           <img src="{{ im.url }}" alt="bisp">
                        {% endthumbnail %}
                      {% endif %}

               </div>

                  <div class="col-md-4">
                              <div class="form-group">
                                  <a href="{% url 'marketing:calendar' %}"  target="_blank"><i class="fa fa-calendar"></i> <label>  Future Follow-up</label></a>
                                <span id="id_schedule_later"></span>
                              </div>
                            </div>

                            <div class="col-md-4 timezone-div" style="display: none;">
                              <div class="form-group">
                                <label>Schedule Date Time</label><span class="error_marker" style="color:red">
                                  *</span>
                                <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                                  <input type="text" class="form-control datetimepicker-input"
                                    data-target="#datetimepicker1" name="schedule_date_time" />
                                  <div class="input-group-append" data-target="#datetimepicker1"
                                    data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                  </div>
                                </div>
                                <!-- <input type="text" class="form-control" name="schedule_date_time" value="" placeholder="Schedule Date Time"> -->
                                <span id="id_schedule_date_time"></span>
                              </div>
                            </div>

              <div class="received_msg">
                <div class="received_withd_msg">

                      {% for var_stored_ms in var_stored_msg %}

<!--               {{request.user.id}}-&#45;&#45;{{var_stored_ms.sender_id}}-->
                    {% if var_stored_ms.sender_id == user_obj.id  %}


                          <p>{{var_stored_ms.msg_content}}kkkkk

                          </p>
                     <span class="time_date">{{var_stored_ms.created_at}}</span>
                     {% endif %}
              {% endfor %}


                </div>

              </div>

            </div>
            <div class="outgoing_msg">
              <div class="sent_msg">
                     {% for var_stored_msg in var_stored_msg %}
                       {% if var_stored_msg.reciever_id == user_obj.id %}
                            <p>{{var_stored_msg.msg_content}}</p>
                            <span class="time_date">{{var_stored_msg.created_at}}</span>
                       {% endif %}
                    {% endfor %}

            </div>
            </div>
          <div class="type_msg">
            <div class="input_msg_write">
              <input type="text" name="msg_content" class="write_msg" placeholder="Type a message" />
              <button class="msg_send_btn btb btn-success" type="submit">Send</button>
            </div>
          </div>
        </div>
      </div>




      </div></div></div>
  </form>
    </body>

    </html>
</html>
{% endblock %}

{% block js_block %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-tagsinput/1.3.6/jquery.tagsinput.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="https://malsup.github.com/jquery.form.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"></script>
<script type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>


{% endblock js_block %}