bispenv/Django-CRM-master/crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('marketing/', include('marketing.urls', namespace="marketing")),
    path('myapp/', include('myapp.urls', namespace="myapp")),

    path('Leadanalytics/', include('LeadApplication.urls')),


    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

bispenv/Django-CRM-master/marketing/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import (
    dashboard, contact_lists, contacts_list, contact_list_new, contacts_list_new, contact_list_detail, edit_contact,

    edit_contact_list, delete_contact_list, failed_contact_list_detail, failed_contact_list_download_delete,
  demo_file_download, delete_contact,  contact_detail,
    edit_failed_contact, delete_failed_contact,func_chat_detail,fun_calendar,fun_add_event,fun_remove,fun_update,BasicUploadView,clear_database,
link_contacts_list,link_contact_detail, func_link_chat_detail, fun_export_users_xls,fun_read_pdf,event_list_detail,
)

app_name = 'marketing'

urlpatterns = [
    path('', dashboard, name='dashboard'),

    path('contact-list/', contact_lists, name='contact_lists'),
    path('contacts/<int:pk>/edit/', edit_contact, name='edit_contact'),
    path('contacts/<int:pk>/delete/', delete_contact, name='delete_contact'),

    path('contacts/', contacts_list, name='contacts_list'),
    path('contact-list/create/', contact_list_new, name='contact_list_new'),
    path('cl/list/cnew/', contacts_list_new, name='contacts_list_new'),
    path('contact-list/<int:pk>/detail/', contact_list_detail, name='contact_list_detail'),
    path('contact-list/<int:pk>/failed/', failed_contact_list_detail, name='failed_contact_list_detail'),
    path('contact-list/<int:pk>/failed/edit/', edit_failed_contact, name='edit_failed_contact'),
    path('contact-list/<int:pk>/failed/delete/', delete_failed_contact, name='delete_failed_contact'),
    path('contact-list/<int:pk>/failed/download/',
         failed_contact_list_download_delete, name='failed_contact_list_download_delete'),
    path('contact-list/<int:pk>/edit/', edit_contact_list, name='edit_contact_list'),
    path('contact-list/<int:pk>/delete/', delete_contact_list, name='delete_contact_list'),


    path('demo-file-download-for-contacts-list/', demo_file_download, name='demo_file_download'),

    path('contacts/<int:contact_id>/view/', contact_detail, name="contact_detail"),
    path('contacts/<str:user_id>/chatdetail/', func_chat_detail, name="func_chat_detail"),
    path('contacts/calendar/', fun_calendar, name='calendar'),
    path('contacts/add_event/', fun_add_event, name='fun_add_event'),
    path('contacts/update/', fun_update, name='fun_update'),
    path('contacts/remove/', fun_remove, name='fun_remove'),


    url(r'^basic-upload/$', BasicUploadView.as_view(), name='basic_upload'),
    url(r'^clear/$', clear_database, name='clear_database'),
    url(r'^pdf/$', fun_read_pdf, name='fun_read_pdf'),
    path('linkcontacts/', link_contacts_list, name='linkcontacts_list'),
    path('linkcontacts/<int:contact_id>/view/', link_contact_detail, name="link_contact_detail"),
    path('linkcontacts/<str:user_id>/chatdetail/',  func_link_chat_detail, name="func_link_chat_detail"),
    url(r'^export/xls/$', fun_export_users_xls, name='export_users_xls'),


    path('event-list/<int:pk>/detail/', event_list_detail, name='event_list_detail'),

]

bispenv/Django-CRM-master/marketing/models.py
from datetime import datetime, timedelta
from django.db import models
from django.utils.timesince import timesince
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator
from common.models import User


class Pdf(models.Model):
    title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to='contacts/pdfs/')
    uploaded_at = models.DateTimeField(auto_now_add=True)


class Contactlinkedin(models.Model):
    created_by = models.ForeignKey(
        User, related_name="marketing_contactlinkedin",
        null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=500)
    email = models.EmailField()
    contact_number = models.CharField(
      max_length=20, blank=True, null=True)

    company_name = models.CharField(max_length=500, null=True, blank=True)
    last_name = models.CharField(max_length=500, null=True, blank=True)
    city = models.CharField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=500, null=True, blank=True)
    country = models.CharField(max_length=500, null=True, blank=True)
    skills = models.CharField(max_length=500, null=True, blank=True)
    language=models.CharField(max_length=500, null=True, blank=True)
    certification =models.CharField(max_length=500, null=True, blank=True)


    position = models.CharField(max_length=500, null=True, blank=True)


    def __str__(self):
        return self.email

    class Meta:
        ordering = ['id', ]


class Tag(models.Model):
    name = models.CharField(max_length=500)
    color = models.CharField(max_length=20,
                             default="#999999", verbose_name=_("color"))
    created_by = models.ForeignKey(User,
                                   related_name="marketing_tags",
                                   null=True, on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)

    @property
    def created_by_user(self):
        return self.created_by if self.created_by else None

class ContactList(models.Model):
    created_by = models.ForeignKey(
        User, related_name="marketing_contactlist",
        null=True, on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=500)
    tags = models.ManyToManyField(Tag)
    visible_to = models.ManyToManyField(User, related_name="contact_lists_visible_to")

    class Meta:
        ordering = ('id',)

    @property
    def created_by_user(self):
        return self.created_by if self.created_by else None

    @property
    def created_on_format(self):
        return self.created_on.strftime('%b %d, %Y %I:%M %p')

    @property
    def created_on_since(self):
        now = datetime.now()
        difference = now.replace(tzinfo=None) - \
            self.created_on.replace(tzinfo=None)

        if difference <= timedelta(minutes=1):
            return 'just now'
        return '%(time)s ago' % {
            'time': timesince(self.created_on).split(', ')[0]}

    @property
    def tags_data(self):
        return self.tags.all()

    @property
    def no_of_contacts(self):
        return self.contacts.all().count()

    @property
    def no_of_campaigns(self):
        return self.campaigns.all().count()

    @property
    def unsubscribe_contacts(self):
        return self.contacts.filter(is_unsubscribed=True).count()

    @property
    def bounced_contacts(self):
        return self.contacts.filter(is_bounced=True).count()

class Contact(models.Model):
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'. \
        Up to 20 digits allowed."
    )
    created_by = models.ForeignKey(
        User, related_name="marketing_contacts_created_by",
        null=True, on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    date = models.DateTimeField(auto_now=True)
    contact_list = models.ManyToManyField(ContactList, related_name="contacts")
    name = models.CharField(max_length=500)
    email = models.EmailField()
    contact_number = models.CharField(
      max_length=20, blank=True, null=True)
    is_unsubscribed = models.BooleanField(default=False)
    is_bounced = models.BooleanField(default=False)
    company_name = models.CharField(max_length=500, null=True, blank=True)
    last_name = models.CharField(max_length=500, null=True, blank=True)
    city = models.CharField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=500, null=True, blank=True)
    country = models.CharField(max_length=500, null=True, blank=True)
    Course = models.CharField(max_length=500, null=True, blank=True)
    Lead_Source = models.CharField(max_length=500, null=True, blank=True)
    position = models.CharField(max_length=500, null=True, blank=True)
    pdf_file = models.FileField(upload_to='contacts/pdfs/',null=True,blank=True)

    def __str__(self):
        return self.email

    class Meta:
        ordering = ['id', ]

class Message(models.Model):
     sender = models.ForeignKey(User, related_name="sender",on_delete=models.CASCADE)
     reciever = models.ForeignKey(User, related_name="reciever",on_delete=models.CASCADE)
     linkedin_contact = models.ForeignKey(Contact, related_name="linkedin",on_delete=models.CASCADE,default=8)
     msg_content =models.TextField()
     created_at = models.DateTimeField(auto_now_add=True)
     schedule_date_time = models.DateTimeField(blank=True, null=True)


class linkMessage(models.Model):
    sender = models.ForeignKey(User, related_name="linksender", on_delete=models.CASCADE)
    reciever = models.ForeignKey(User, related_name="linkreciever", on_delete=models.CASCADE)
    linkedin_contact = models.ForeignKey(Contactlinkedin, related_name="contactlinkedin", on_delete=models.CASCADE)
    msg_content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    schedule_date_time = models.DateTimeField(blank=True, null=True)

from django.urls import reverse

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    user = models.ForeignKey(User, related_name="user", on_delete=models.CASCADE,default=1)

    @property
    def get_html_url(self):
        url = reverse('marketing:event_details', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

class FailedContact(models.Model):
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'.\
        Up to 20 digits allowed."
    )
    created_by = models.ForeignKey(
        User, related_name="marketing_failed_contacts_created_by", null=True,
        on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)
    contact_list = models.ManyToManyField(
        ContactList, related_name="failed_contacts")
    name = models.CharField(max_length=500, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    contact_number = models.CharField(
        validators=[phone_regex], max_length=20, blank=True, null=True)
    company_name = models.CharField(max_length=500, null=True, blank=True)
    last_name = models.CharField(max_length=500, null=True, blank=True)
    city = models.CharField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=500, null=True, blank=True)
    country = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.email

bispenv/Django-CRM-master/templates/marketing/lists/all.html
{% extends 'marketing/base.html' %}
{% load staticfiles %}
{% load paginate %}
{% block content %}
{{ block.super }}

{% block extralinks %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
  <link rel="icon" type="image/png" href="{%static 'images/favicon.ico'%}"/>
{% endblock extralinks %}

<div class="main_container ml-5 mr-5">
  <div class="row marl">

    <div class="filter_row list_filter_row row marl col-md-12 mb-2">
      <div class="">
        <div class="card">
          <div class="card-body">
            <form id="leads_filter" action="" method="POST">
              <div class="card-body ">
                <div class="card-title">Filter</div>
                <div class="row marl">
                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Name</label>
                      <input type="text" class="form-control" placeholder="Contact Name" name="contact_name"
                        value="{{request.POST.contact_name}}">
                    </div>
                  </div>
                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Email</label>
                      <input type="text" class="form-control" placeholder="Contact Email" name="contact_email"
                        value="{{request.POST.contact_email}}">
                    </div>
                  </div>

                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Position</label>
                      <select name="contact_position" class="id_tag" class="assigned_users_ form-control">
                          <option value="">select</option>
                          {% for contact in contacts %}
                          <option value="{{contact.position}}" {% if contact.position|slugify == request.POST.position %} selected="" {% endif %}>
                          {{contact.position}}</option>
                          {% endfor %}
                        </select>
<!--                      <input type="text" class="form-control" placeholder="Position" name="contact_position"-->
<!--                        value="{{request.POST.position}}">-->
                    </div>
                  </div>
                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Company Name</label>
                      <select name="contact_company_name" class="id_tag" class="assigned_users_ form-control">
                        <option value="">select</option>
                        {% for contact in contacts %}
                        <option value="{{contact.company_name}}" {% if contact.company_name|slugify == request.POST.contact_company_name %} selected=""
                          {% endif %}>
                          {{contact.company_name}}</option>
                        {% endfor %}
                      </select>
                    </div>
                  </div>
                  <input type="hidden" name="tab_status" id="tab_status">
                  <div class="filter_col col-2">
                    <div class="form-group buttons_row">
                      <button class="btn btn-primary save" type="submit">Search</button>
                      <a href="" class="btn btn-default clear" onclick="window.location.reload">Clear</a>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="table_container_row no_mar_top">
        <div class="card">
          <div class="card-body">
            <div class="card-title text-right">
              <span class="float-left">Contacts - {{ contacts|length }}</span>
              <span class="filter_toggle">
                <a href="#" class="primary_btn"><i class="fa fa-filter"></i></a>
              </span>
              <a href="{% url 'marketing:contact_list_new' %}" class="primary_btn">Add New Contact List</a>
              <a class="primary_btn" onclick="exportTableToCSV('Contacts.csv')" style="color:white;">Export all Contacts</a>
            </div>
            <div class="table-responsive table-bordered ">
              <table class="table">
                {% if contacts %}
                <thead>
                  <tr>
                    <th class="text-center" width="5%">S. No</th>
                    <th class="text-center" width="13%">Contact Name</th>
                    <th class="text-center" width="13%">Email</th>
                    <th class="text-center" width="13%">Company</th>
                    <th class="text-center" width="13%">Position</th>
                    <th class="text-center" width="13%">Related Connection</th>
                    {% if request.user.role == "ADMIN"  or request.user.is_superuser %}
                      <th class="text-center" width="13%">User Account</th>
                    {% endif %}
                    <th class="text-center" width="13%">Actions</th>
                  </tr>
                </thead>
                {% endif %}
                <tbody>
                  {% if per_page %}
                  {% paginate per_page contacts %}
                  {% else%}
                  {% paginate 10 contacts %}
                  {% endif %}
                  {% for contact in contacts %}
                  <tr style="text-align:center;">
                    <td scope="row" class="text-center">{{ forloop.counter }}</td>
                    <td><a href="{% url 'marketing:contact_detail' contact.id %}">{{ contact.name }} {{ contact.last_name }}</td>
                    <td class="text-center">{{ contact.email }}</td>
                    <td class="text-center">{{ contact.company_name }}</td>
                    <td class="text-center">{{ contact.position }}</td>
                    <td>
                      {% for contact_list in contact.contact_list.all %}
                      <span> <a
                          href="{% url 'marketing:contact_list_detail' contact_list.id %}">{{contact_list.name}}</a>
                      </span>
                      {% endfor %}
                      {% if request.user.role == "ADMIN"  or request.user.is_superuser %}
                        <td>{{ contact.created_by.first_name }} {{contact.created_by.last_name }}</td>
                      {% endif %}
                    <td class="actions text-center">
                      <a href="{% url 'marketing:edit_contact' contact.id %}" class="btn btn-success edit edit_contact"
                        data-other-contacts-lists='{{contact.contact_list.all|length}}'><i class="fas fa-edit"></i></a>
                      <a href="{% url 'marketing:delete_contact' contact.id %}"
                        class="btn btn-danger delete remove_account"
                        data-other-contacts-lists='{{contact.contact_list.all|length}}'><i
                          class="fas fa-trash-alt"></i></a>
                    </td>
                  </tr>
                  {% empty %}
                  <tr style="text-align:center;">
                    <td colspan="6">No records found!</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="marl row text-center mt-5">
        {% show_pages %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js_block %}
<script>
  $(function () {
    $(".filter_toggle").click(function () {
      $(".list_filter_row").toggle();

    });
    $('.id_tag').select2();

    $("a[rel='page']").click(function (e) {
      e.preventDefault();
      $('#leads_filter').attr("action", $(this).attr("href"));
      $('#leads_filter').submit();
    });

     var opt = {};
    $(".id_tag > option").each(function () {
        if(opt[$(this).text()]) {
            $(this).remove();
        } else {
            opt[$(this).text()] = $(this).val();
        }
    });

    $(".remove_account").click(function (e) {
      e.preventDefault()
      url = $(this).attr('href')
      var contact_lists = parseInt($(this).attr('data-other-contacts-lists'));
      if (contact_lists > 1) {
        if (!confirm('Are you sure you want to delete? this contact exists in other contact lists, deleting this will delete this contact from other contact lists too!'))
          return;
        window.location = $(this).attr('href');
      } else {
        if (!confirm('Are you sure you want to delete?'))
          return;
        window.location = $(this).attr('href');
      }
    })

    $(".edit_contact").click(function (e) {
      e.preventDefault()
      url = $(this).attr('href')
      console.log(url)
      var contact_lists = parseInt($(this).attr('data-other-contacts-lists'));
      console.log(contact_lists);
      if (contact_lists > 1) {
        if (!confirm('Are you sure you want to edit? this contact exists in other contact lists, editing this will change this contact information in other contact lists too!'))
          return;
        window.location = $(this).attr('href');
      } else {
        window.location = $(this).attr('href');
      }
    })
  })

function downloadCSV(csv, filename) {
  var csvFile;
  var downloadLink;

  csvFile = new Blob([csv], {
    type: "text/csv"
  });

  downloadLink = document.createElement("a");
  downloadLink.download = filename;
  downloadLink.href = window.URL.createObjectURL(csvFile);

  downloadLink.style.display = "none";

  document.body.appendChild(downloadLink);

  downloadLink.click();
}

function exportTableToCSV(filename) {
  var csv = [];
  var rows = document.querySelectorAll("table tr");

  for (var i = 0; i < rows.length; i++) {
    var row = [],
      cols = rows[i].querySelectorAll("td, th");
    for (var j = 0; j < cols.length; j++)
      row.push(cols[j].innerText);

    csv.push(row.join(","));
  }
  //download csv file
  downloadCSV(csv.join("\n"), filename);

}

</script>
{% endblock js_block %}

bispenv/Django-CRM-master/templates/marketing/lists/detail.html
{% extends 'marketing/base.html' %}
{% load staticfiles %}
{% load paginate %}
{% block content %}
{{ block.super }}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb mb-5">
    <li class="breadcrumb-item"><a href="{% url 'marketing:contact_lists' %}">Contact Lists</a></li>
    <li class="breadcrumb-item active">{{contact_list.name}}</li>
  </ol>
</nav>
<div class="main_container ml-5 mr-5">
  <div class="row marl">
    <div class="filter_row list_filter_row row marl col-md-12 mb-2">
      <div class="">
        <div class="card">
          <div class="card-body">
            <form id="leads_filter" action="" method="POST">
              <div class="card-body ">
                <div class="card-title">Filters</div>
                <div class="row marl">
                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Name</label>
                      <input type="text" class="form-control" placeholder="Name" name="name"
                        value="{{request.POST.name}}">
                    </div>
                  </div>
                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Email</label>
                      <input type="text" class="form-control" placeholder="Email" name="email"
                        value="{{request.POST.email}}">
                    </div>
                  </div>
                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Company Name</label>
                      <input type="text" class="form-control" placeholder="Company Name" name="company_name"
                        value="{{request.POST.company_name}}">
                    </div>
                  </div>

                   <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Position</label>
                      <input type="text" class="form-control" placeholder="Position" name="position"
                        value="{{request.POST.position}}">
                    </div>
                  </div>
                  <input type="hidden" name="tab_status" id="tab_status">
                  <div class="filter_col col-2">
                    <div class="form-group buttons_row">
                      <button class="btn btn-primary save" type="submit">Search</button>
                      <a href="" class="btn btn-default clear" onclick="window.location.reload">Clear</a>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="table_container_row no_mar_top">
        <div class="card">
          <div class="card-body">
            <div class="card-title text-right">
              <span class="float-left">{{ contact_list.name }} - {{ contacts_list|length }}</span>
              {% if contact_list.failed_contacts.all|length > 0 %}
              <a href="{% url 'marketing:failed_contact_list_detail' contact_list.id %}" class="primary_btn">Failed
                Contacts</a>
              {% endif %}
              <span class="filter_toggle">
                <a href="#" class="primary_btn"><i class="fas fa-filter"></i></a>
              </span>
              <a href="{% url 'marketing:contact_list_new' %}" class="primary_btn">Add New Contact List</a>
            </div>
            <div class="table-responsive table-bordered ">
              <table class="table">
                <thead>
                  <tr>
                    <th class="text-center" width="5%">ID</th>
                    <th class="text-center" width="20%">Contact Name</th>
                    <th class="text-center" width="20%">Email</th>
                     <th class="text-center" width="20%">Company Name</th>
                     <th class="text-center" width="20%">Position</th>

                    <th width="10%">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <span><b>Tags : </b></span>
                    {% for tag in contact_list.tags.all %}
                    <span class="text-left color{{forloop.counter}} tag_class_cl" id="list_tag" data-link="{{tag.id}}"
                      style="cursor: pointer;">{{tag.name}}</span>
                    {% empty %}
                    <span class="text-left">No Tags</span>
                    {% endfor %}
                  </tr>
                  {% if per_page %}
                  {% paginate per_page contacts_list %}
                  {% else%}
                  {% paginate 10 contacts_list %}
                  {% endif %}
                  {% for contact in contacts_list %}
                  <tr style="text-align:center;">
                    <td scope="row" class="text-center">{{ forloop.counter }}</td>
                    <td> <a href="{% url 'marketing:contact_detail' contact.id %}" target="_blank">{{ contact.name }} {{contact.last_name}}</a> </td>
                    <td class="text-center"> <a href="{% url 'marketing:contact_detail' contact.id %}">{{ contact.email }}</a> </td>
                    <td class="text-center">{{contact.company_name}}</td>
                    <td class="text-center">{{contact.position }}</td>
                    <td class="actions" class="text-center">
                      <a href="{% url 'marketing:edit_contact' contact.id %}?from_contact={{contact_list.id}}"
                        class="btn btn-success edit edit_contact"
                        data-other-contacts-lists='{{contact.contact_list.all|length}}'><i class="fas fa-edit"></i></a>
                      <!-- <a href="/contacts/1/edit/" class="btn btn-info duplicate"><i class="fas fa-copy"></i></a> -->
                      <a href="{% url 'marketing:delete_contact' contact.id %}?from_contact={{contact_list.id}}"
                        class="btn btn-danger delete remove_account"
                        data-other-contacts-lists='{{contact.contact_list.all|length}}'><i class="fas fa-trash"></i></a>


                    </td>
                  </tr>
                  {% empty %}
                  <tr style="text-align:center;">
                    <td colspan="6">No records found!</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="marl row text-center mt-5">
    {% show_pages %}
  </div>
</div>
{% endblock %}

{% block js_block %}
<script>
  $(function () {
    $(".filter_toggle").click(function () {
      $(".list_filter_row").toggle();

    });
    $('#id_tag').select2();

    // $(".remove_account").click(function (e) {
    //   e.preventDefault()
    //   url = $(this).attr('href')
    //   if (!confirm('Are you sure you want to delete?'))
    //     return;
    //   window.location = $(this).attr('href')
    // })

    $(".remove_account").click(function (e) {
      e.preventDefault()
      url = $(this).attr('href')
      var contact_lists = parseInt($(this).attr('data-other-contacts-lists'));
      if (contact_lists > 1) {
        if (!confirm('Are you sure you want to delete? this contact exists in other contact lists, deleting this will delete this contact from other contact lists too!'))
          return;
        window.location = $(this).attr('href');
      } else {
        if (!confirm('Are you sure you want to delete?'))
          return;
        window.location = $(this).attr('href');
      }
    })

    $(".edit_contact").click(function (e) {
      e.preventDefault()
      url = $(this).attr('href')
      console.log(url)
      var contact_lists = parseInt($(this).attr('data-other-contacts-lists'));
      console.log(contact_lists);
      if (contact_lists > 1) {
        if (!confirm('Are you sure you want to edit? this contact exists in other contact lists, editing this will change this contact information in other contact lists too!'))
          return;
        window.location = $(this).attr('href');
      } else {
        window.location = $(this).attr('href');
      }
    })

    $("a[rel='page']").click(function (e) {
      e.preventDefault();
      $('#leads_filter').attr("action", $(this).attr("href"));
      $('#leads_filter').submit();
    });
  })
</script>
{% endblock js_block %}

bispenv/Django-CRM-master/templates/marketing/lists/event.html
{% extends 'marketing/base.html' %}
{% load staticfiles %}
{% load compress %}

{% block title %}
Event
{% endblock %}

<head>

	{% load sass_tags %}
    <link href="{% sass_src 'E:/analytyics_leads_opportunity_pdf/bispenv/Django-CRM-master/static/css/style.scss' %}" rel="stylesheet">

</head>
{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'marketing:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}