bispenv/Django-CRM-master/LeadApplication/urls.py
from django.urls import path
from django.conf.urls import include,url
from LeadApplication import views
from LeadApplication import analytics
from LeadApplication import dashboard
app_name = "LeadApplication"

urlpatterns = [
    # path('handler404',views.handler404,name='handler404'),

    path('', views.fun_homePage, name='fun_homePage'),
    path('upload_csv/',views.fun_upload_csv,name='fun_upload_csv'),

    path('lead_analytics/<str:changed_prefrence>', views.fun_leadAnalytics,name='lead_analytics'),


    # path('fun_joy/', views.fun_joy,name='fun_joy'),

    path('download_csv/<str:choice>',views.download_csv,name='download_csv'),


    path('fun_select_parameters/<str:currentAccordId>', views.fun_select_parameters, name='fun_select_parameters'),
    path('fun_setPreference/',views.fun_setPreference,name = 'fun_setPreference'),
    # path('leadanalytics/<str:ch>',views.change_pref,name='change_pref'),
    path('getRelatedWords/',views.getRelatedWords,name='getRelatedWords'),
    path('getKeywordChart/',views.getKeywordChart,name='getKeywordChart'),

    #from here we are going to start the enhanced view
    #for example path('abcd/',enhancedViews.getkeyword,name='getkeyword'),
    #here we will create a new view with the name of enhancedViews

    path('analytics/',analytics.analytics,name='analytics'),
    path('getSelectedIntervalChart/',analytics.getChart,name='getSelectedIntervalChart'),
    path('CountrySpecificLeads/',analytics.getCountrySpecificChart,name='CountrySpecificLeads'),
    path('TechnologySpecificLeads/',analytics.getTechnologySpecificChart,name='TechnologySpecificLeads'),
    path('trial/',analytics.trial,name='trial'),
    path('dashboard/',dashboard.fun_analytics_dashboard,name='analytics_dashboard'),

    # path('fun_getchartjs/', dashboard.fun_getchartjs, name='fun_getchartjs'),
    path('past_reports/',dashboard.fun_past_reports,name='past_reports'),
    # path('api/data/',dashboard.fun_past_reports,name='api-data'),

]

bispenv/Django-CRM-master/common/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from common.views import (
    HomeView, LoginView, ForgotPasswordView, LogoutView,
    ChangePasswordView, ProfileView,
    UsersListView, CreateUserView, UpdateUserView, UserDetailView,
    UserDeleteView, PasswordResetView,
    DocumentListView, document_create, document_update,
    DocumentDetailView, DocumentDeleteView,
    download_document, change_user_status, download_attachment,
    add_comment, edit_comment, remove_comment,
    api_settings, add_api_settings, view_api_settings,
    update_api_settings, delete_api_settings,
    change_passsword_by_admin, google_login,getComperison,
    # Senddata
)
from django.conf.urls.static import static
from django.conf import settings


app_name = 'common'


urlpatterns = [
    path('', HomeView, name='home'),
    # path('senddata/', Senddata, name='senddata'),


    path('login/', LoginView.as_view(), name='login'),
    path('forgot-password/',
         ForgotPasswordView.as_view(), name='forgot_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/',
         ChangePasswordView.as_view(), name='change_password'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # User views
    path('users/list/', UsersListView.as_view(), name='users_list'),
    path('users/create/', CreateUserView.as_view(), name='create_user'),
    path('users/<int:pk>/edit/', UpdateUserView.as_view(), name="edit_user"),
    path('users/<int:pk>/view/', UserDetailView.as_view(), name='view_user'),
    path('users/<int:pk>/delete/',
         UserDeleteView.as_view(), name='remove_user'),

    path(
        'password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # Document
    path('documents/', DocumentListView.as_view(), name='doc_list'),
    path('documents/create/', document_create, name='create_doc'),
    path('documents/<int:pk>/edit/', document_update, name="edit_doc"),
    path('documents/<int:pk>/view/',
         DocumentDetailView.as_view(), name='view_doc'),
    path('documents/<int:pk>/delete/',
         DocumentDeleteView.as_view(), name='remove_doc'),

    # download
    path('documents/<int:pk>/download/',
         download_document, name='download_document'),

    # download_attachment
    path('attachments/<int:pk>/download/',
         download_attachment, name='download_attachment'),

    path('user/status/<int:pk>/',
         change_user_status, name='change_user_status'),

    path('comment/add/', add_comment, name="add_comment"),
    path('comment/<int:pk>/edit/', edit_comment, name="edit_comment"),
    path('comment/remove/', remove_comment, name="remove_comment"),

    # settings
    path('api/settings/', api_settings, name="api_settings"),
    path('api/settings/add/', add_api_settings, name="add_api_settings"),
    path('api/settings/<int:pk>/',
         view_api_settings, name="view_api_settings"),
    path('api/settings/<int:pk>/update/',
         update_api_settings, name="update_api_settings"),
    path('api/settings/<int:pk>/delete/',
         delete_api_settings, name="delete_api_settings"),

    path('change-password-by-admin/', change_passsword_by_admin,
         name="change_passsword_by_admin"),
    path('google/login/', google_login, name="google_login"),






] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bispenv/Django-CRM-master/crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('marketing/', include('marketing.urls', namespace="marketing")),
    path('myapp/', include('myapp.urls', namespace="myapp")),

    path('Leadanalytics/', include('LeadApplication.urls')),


    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

bispenv/Django-CRM-master/marketingold/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import (
    dashboard, contact_lists, contacts_list, contact_list_new, contacts_list_new, contact_list_detail, edit_contact,

    edit_contact_list, delete_contact_list, failed_contact_list_detail, failed_contact_list_download_delete,
  demo_file_download, delete_contact,  contact_detail,
    edit_failed_contact, delete_failed_contact,func_chat_detail,fun_calendar,fun_add_event,fun_remove,fun_update,BasicUploadView,clear_database,
link_contacts_list,link_contact_detail, func_link_chat_detail, fun_export_users_xls,fun_read_pdf,event_list_detail
)

app_name = 'marketing'

urlpatterns = [
    path('', dashboard, name='dashboard'),

    path('contact-list/', contact_lists, name='contact_lists'),
    path('contacts/<int:pk>/edit/', edit_contact, name='edit_contact'),
    path('contacts/<int:pk>/delete/', delete_contact, name='delete_contact'),

    path('contacts/', contacts_list, name='contacts_list'),
    path('contact-list/create/', contact_list_new, name='contact_list_new'),
    path('cl/list/cnew/', contacts_list_new, name='contacts_list_new'),
    path('contact-list/<int:pk>/detail/', contact_list_detail, name='contact_list_detail'),
    path('contact-list/<int:pk>/failed/', failed_contact_list_detail, name='failed_contact_list_detail'),
    path('contact-list/<int:pk>/failed/edit/', edit_failed_contact, name='edit_failed_contact'),
    path('contact-list/<int:pk>/failed/delete/', delete_failed_contact, name='delete_failed_contact'),
    path('contact-list/<int:pk>/failed/download/',
         failed_contact_list_download_delete, name='failed_contact_list_download_delete'),
    path('contact-list/<int:pk>/edit/', edit_contact_list, name='edit_contact_list'),
    path('contact-list/<int:pk>/delete/', delete_contact_list, name='delete_contact_list'),


    path('demo-file-download-for-contacts-list/', demo_file_download, name='demo_file_download'),

    path('contacts/<int:contact_id>/view/', contact_detail, name="contact_detail"),
    path('contacts/<str:user_id>/chatdetail/', func_chat_detail, name="func_chat_detail"),
    path('contacts/calendar/', fun_calendar, name='calendar'),
    path('contacts/add_event/', fun_add_event, name='fun_add_event'),
    path('contacts/update/', fun_update, name='fun_update'),
    path('contacts/remove/', fun_remove, name='fun_remove'),


    url(r'^basic-upload/$', BasicUploadView.as_view(), name='basic_upload'),
    url(r'^clear/$', clear_database, name='clear_database'),
    url(r'^pdf/$', fun_read_pdf, name='fun_read_pdf'),
    path('linkcontacts/', link_contacts_list, name='linkcontacts_list'),
    path('linkcontacts/<int:contact_id>/view/', link_contact_detail, name="link_contact_detail"),
    path('linkcontacts/<str:user_id>/chatdetail/',  func_link_chat_detail, name="func_link_chat_detail"),
    url(r'^export/xls/$', fun_export_users_xls, name='export_users_xls'),


    path('event-list/<int:pk>/detail/', event_list_detail, name='event_list_detail'),

]

bispenv/Django-CRM-master/myapp/urls.py
from django.urls import path
from django.conf.urls import include, url
from myapp import views,regression,timeseries,forecasting,leads

app_name = "myapp"

urlpatterns = [
    # path('handler404',views.handler404,name='handler404'),

    path('', views.login1,name='login'),
    path('index/', views.index, name='index'),

    path('home/', views.Home, name='home'),
    path('userhome/', views.userhome, name='userhome'),
    path('userlogin/', views.userlogin, name='userlogin'),
    path('upload/', views.file_upload, name='upload'),
    path('technology/', views.technology, name='technology'),
    path('visual/', views.visual, name='visual'),
    path('dashboard/<str:name>', views.dashboard, name='dashboard'),
    path('Technology/', views.Technology, name='Technology'),
    path('Location/', views.Location, name='Location'),
    path('Experience/', views.Experience, name='Experience'),
    path('Company/', views.Company, name='Company'),
    path('Salary/', views.Salary, name='Salary'),
    url(r'^pdf/$', views.GeneratePdf.as_view(), name='pdf'),


#REgression Urls
   path('regression/<str:name>', regression.regression, name='regression'),
   path('predictive_analysis/', regression.predictive_analysis, name='predictive_analysis'),




#TimeSeries Urls
   path('time_series_analysis/', timeseries.time_series_analysis, name='time_series_analysis'),
# url(r'^timeanalysis/(?P<name>[\w|\W]+)'.replace('%20','-'), timeseries.timeanalysis, name='timeanalysis'),

#(r’^operationstatus/(?P<status>.*)$’, ‘myapp.backbone_view’)
   path('timeanalysis/<str:name>', timeseries.timeanalysis, name='timeanalysis'),
    # path('post/<slug>', timeseries.post, name='post'),

#forecasting Urls

    path('forecasting/', forecasting.forecasting, name='forecasting'),
    path('Prediction/<str:name>', forecasting.Prediction, name='Prediction'),


#Lead url
    path('leadanalytics/', leads.leadanalytics, name='leadanalytics'),
]
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bispenv/Django-CRM-master/templates/marketingold/_modal.html
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

bispenv/Django-CRM-master/templates/marketingold/base.html
{% extends 'root.html' %}

{% block main_menu %}
<ul class="navbar-nav mr-auto">
  <!-- add submenu for contacts-->
  <div class="btn-group">
    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
      style="box-shadow: none; color: #657b88">
      Lead Analytics
    </button>
    <div class="dropdown-menu mt-2">
      <a class="dropdown-item contact-list" id="common-dashboard" href="http://192.168.1.27:8000/">Dashboard</a>
      <a class="dropdown-item contact-list" id="filuploads" href="{% url 'LeadApplication:analytics_dashboard' %}">Lead Analytics</a>
    </div>
  </div>
<!--  <li class="nav-item"></li>-->
<!--  <li class="nav-item"><a class="nav-link" id="marketing-dashboard" href="{% url 'marketing:dashboard' %}">Linkedin</a></li>-->
  <li class="nav-item mt-2 contact_class" id="contact">
  <div class="btn-group">
    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
      style="box-shadow: none; color: #657b88">
      Smart Connect
    </button>
    <div class="dropdown-menu mt-2">
      <a class="nav-link" id="marketing-dashboard" href="{% url 'marketing:dashboard' %}">Dashboard</a>
      <a class="dropdown-item contact-list" id="contact-list" href="{% url 'marketing:contact_lists' %}" >Contacts List</a>

      <a class="dropdown-item contacts" id="contacts" href="{% url 'marketing:contacts_list' %}" >Contacts</a>
      <a class="nav-link" id="filupload" href="{% url 'marketing:basic_upload' %}">Pdf Upload</a>

    </div>
  </div>
</li>
<!--  <li class="nav-item"></li>-->
<!--  <li class="nav-item"><a class="nav-link" id="filuploads" href="{% url 'LeadApplication:lead_analytics' 'leads' %}">Lead Analytics</a></li>-->
<!--  <li class="nav-item"></li>-->

  <li class="nav-item"><a href="{% url 'myapp:index' %}" >Opportunity Analytics</a></li>
</ul>
{% endblock %}





{% comment %}


{% extends 'root.html' %}
{% load staticfiles %}
{% load compress %}
{% load thumbnail %}
{% block main_menu %}
<!-- <ul class="navbar-nav mr-auto">
</ul> -->
{% endblock %}
{% block header %}

{% endblock header %}

{% block content %}
<div class="side_menu">
  <!-- <div class="logo_block"> -->
  <!-- <a href="#">Django <span class="green_color text-uppercase">Crm</span></a> -->
  <div class="dropdown">
    <a class="dropdown-toggle navbar-brand mt-2 ml-3" href="#" role="button" id="dropdownMenuLink"
      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
      style="color:#000; font-weight: 800; font-size: 1.5em;">
      BISP <span class="green_color text-uppercase" style="color:#7ae847">LMS</span>
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <a class="dropdown-item" href="/">Sales</a>
      <a class="dropdown-item" href="{% url 'marketing:dashboard' %}">Marketing</a>
    </div>
  </div>
  <!-- </div> -->
  <div class="profile_block">
    <ul>

      <li data-toggle="tooltip" data-placement="bottom" title="{{request.user}}">
        <a href="#" class="profile_pic">
          <!-- <img src="https://lh3.googleusercontent.com/-6gBVCn2WaAk/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rd7EWo94Fj0ep0DQa3tDjddczFC3g/s96-c-mo/photo.jpg" alt="profile picture"> -->
          {% if not request.user.profile_pic %}
          <img src="{% static 'images/user.png' %}" alt="Micro profile pic">
          {% else %}
          {% thumbnail request.user.profile_pic "25x25" as im %}
          <img src="{{ im.url }}">
          {% endthumbnail %}
          {% endif %}
        </a>
      </li>

      <li data-toggle="tooltip" data-placement="bottom" title="Users">
        <a href="{% url 'common:users_list' %}" class="sky_blue box"><i class="fas fa-users"></i>
        </a>
      </li>
      <li data-toggle="tooltip" data-placement="bottom" title="Change Password">
        <a href="{% url 'common:change_password' %}" class="red box"><i class="fas fa-key"></i></a>
      </li>
      <li data-toggle="tooltip" data-placement="bottom" title="Profile">
        <a href="{% url 'common:profile' %}" class="green box"><i class="fas fa-user"></i></a>
      </li>
      <li data-toggle="tooltip" data-placement="bottom" title="Logout">
        <a href="{% url 'common:logout' %}" class="purple box"><i class="fas fa-sign-out-alt"></i></a>
      </li>
    </ul>
  </div>
  <div class="menu_block">
    <ul class="main_menu">
      <li class="parent_menu">
        <a href="{% url 'marketing:contact_lists' %}" class="red"><i class="far fa-address-book"></i>Contacts</a>
        <ul class="submenu">
          <li><a href="{% url 'marketing:contacts_list' %}" class="yellow"><i class="fas fa-bars"></i>All Contacts</a>
          </li>
          <li><a href="{% url 'marketing:contact_list_new' %}" class="yellow"><i class="far fa-plus-square"></i>Create
              Contact</a></li>
        </ul>
      </li>


    </ul>
  </div>

</div>

{% endblock %}

{% endcomment %}

bispenv/Django-CRM-master/templates/marketingold/dashboard.html
{% extends 'marketing/base.html' %}
{% load staticfiles %}
{% load common_tags %}
{% load paginate %}
{% block content %}
{{ block.super }}
<script src="{% static 'LeadApplication\\js\\charts_min.js' %}"></script>
<div class="" style="">
  <div class="row marl">
    <div class="col-md-12">
      <!-- Dashboard page will come soon -->


      <div class="row marl justify-content-center">
        <div class="col-md-9">
          <!-- count_blocks_row starts here -->
          <div class="row count_blocks_row">

            <div class="col-md-3">
              <div class="item green">
                <a href="{% url 'marketing:contact_lists' %}">
                  <div class="title">Contacts List</div>
                  <div class="count">{{contacts_list|length}}</div>
                </a>
                <!-- <div class="more"><a href="#">Go Live</a></div> -->
              </div>
            </div>



            <div class="col-md-3">
              <div class="item red">
                <a href="{% url 'marketing:contacts_list' %}">
                  <div class="title">Contacts</div>
                  <div class="count">{{contacts|length}}</div>
                  <!-- <div class="more"><a href="#">Go Live</a></div> -->
                </a>
              </div>
            </div>

              <div class="col-md-3">
              <div class="item yellow">
                <a href="{% url 'marketing:calendar' %}">
                  <div class="title">Events</div>
                  <div class="count">{{event_list|length}}</div>
                  <!-- <div class="more"><a href="#">Go Live</a></div> -->
                </a>
              </div>

            </div>

              <div class="col-md-3">
              <div class="item orange card bg-info text-white">
                <a href="{% url 'marketing:linkcontacts_list' %}">
                  <div class="title">Linkedin Contact list</div>
                  <div class="count">{{link_contacts_list|length}}</div>
                  <!-- <div class="more"><a href="#">Go Live</a></div> -->
                </a>
              </div>
            </div>

          </div>
          <!-- count_blocks_row ends here -->
          <div class="open_sections row">
            <div class="col-md-6 table_container_row">
              <div class="card">
                <div class="card-body">
                  <div class="card-title">
                    <span>Contacts List</span>
                  </div>
                  <div class="table-responsive">
                    {% if contacts_list %}
                    <table class="table">
                      <thead>
                        <tr>
                          <th width="40%">Name</th>
                          <!-- <th width="30%">Assigned To</th> -->
                          <th width="50%">Tags</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for contact in contacts_list|slice:"10" %}
                        <tr>
                          <td><a href="{% url 'marketing:contact_list_detail' contact.id %}">{{contact.name}}</a>
                          </td>

                          <td style="display: block;">
                            {% for tag in contact.tags.all|slice:'3' %}
                            <span class="text-left color{{forloop.counter}} tag_class_cl" id="list_tag"
                              data-link="{{tag.id}}" style="cursor: pointer;">{{tag.name}}</span>
                            {% empty %}
                            <span class="text-left">No Tags</span>
                            {% endfor %}
                            {% if contact.tags.all|length > 3 %}
                            <a href="{% url 'marketing:contact_list_detail' contact.id %}" style="color:white;"><span
                                class="text-left" id="list_tag2">{{contact.tags.all|length|subtract:'3'}}
                                  more
                                </span></a>
                            {% endif %}
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                    {% else %}
                    <p style="text-align:center">There are no records</p>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>

             <div class="col-md-6 table_container_row">
              <div class="card">
                <div class="card-body">
                  <div class="card-title">
                    <span>Upcoming Events List(next 5 days)</span>
                  </div>
                  <div class="table-responsive">
                    {% if contacts_list %}
                    <table class="table">
                      <thead>
                        <tr>
                          <th width="40%">Event Title</th>
                          <th width="40%">Event Description</th>
                          <th width="20%">Date</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for event in event_list|slice:"10" %}
                        <tr>
                          <td><a href="{% url 'marketing:event_list_detail' event.id %}">{{event.title}}</a>
                          </td>
                          <td>
                              <a href="#">{{event.description}}</a>
                          </td>
                          <td>
                            {{ event.start_time|date:"D,dM,Y" }}
                          </td>

                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                    {% else %}
                    <p style="text-align:center">There are no records</p>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-12 table_container_row">
              <h5 >Overall lead growth this year till date</h5>
              <canvas id="multilineChart"></canvas>

            </div>

          </div>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock %}
{% block js_block %}
<script type="text/javascript">

  $(document).ready(function () {
    $(".tag_class_cl").click(function () {
      // $(".tag_class_opp").css('cursor', 'pointer')
      url = "{% url 'marketing:contact_lists' %}"
      url = url + "?tag=" + $(this).attr('data-link')
      window.location.href = url;
    });

    $(".tag_class_camp").click(function (e) {
      e.preventDefault()
      // $(".tag_class_opp").css('cursor', 'pointer')

      url = url + "?tag=" + $(this).attr('data-link')
      window.location.href = url;
    });
  });



//here is the multiline
var canvas = document.getElementById("multilineChart");
var ctx = canvas.getContext('2d');

// Global Options:
Chart.defaults.global.defaultFontColor = 'black';
Chart.defaults.global.defaultFontSize = 16;

var data = {
  labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
  datasets: [{
      label: {{current_year}}+' data',
      fill: true,
      lineTension: 0.1,
      backgroundColor: "rgba(167,105,0,0.4)",
      borderColor: "rgb(167, 105, 0)",
      borderCapStyle: 'butt',
      borderDash: [],
      borderDashOffset: 0.0,
      borderJoinStyle: 'miter',
      pointBorderColor: "white",
      pointBackgroundColor: "black",
      pointBorderWidth: 1,
      pointHoverRadius: 8,
      pointHoverBackgroundColor: "brown",
      pointHoverBorderColor: "yellow",
      pointHoverBorderWidth: 2,
      pointRadius: 4,
      pointHitRadius: 10,
      // notice the gap in the data and the spanGaps: false
      data: {{currenty}},
      spanGaps: false,
    }]
};

// Notice the scaleLabel at the same level as Ticks
var options = {
  scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true,
                    stepSize: 100,
                },
                scaleLabel: {
                     display: true,
                     labelString: 'Lead Counts',
                     fontSize: 20
                  }
            }],
            xAxes: [{

                scaleLabel: {
                     display: true,
                     labelString: 'Months('+{{current_year}}+')',
                     fontSize: 20
                  }
            }]
        }
};

// Chart declaration:
var myBarChart = new Chart(ctx, {
  type: 'line',
  data: data,
  options: options
});




</script>
{% endblock js_block %}

bispenv/Django-CRM-master/templates/marketingold/pdf.html
{% load static %}

{% block title %} Upload{% endblock %}

<head>
    <link href="{% static 'F:/Bisp-linkedin-data/bisenv/Django-CRM-master/static/css/bootstrap.min.scss' %}" rel="stylesheet">
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
</head>
{% block javascript %}


  {# JQUERY FILE UPLOAD SCRIPTS #}
  <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>


  {# PHOTOS PAGE SCRIPTS #}
  <script src="{% static 'js/basic-upload.js' %}"></script>
{% endblock %}

{% block photos_content %}

 <form method="post" action="{% url 'marketing:clear_database' %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <button type="submit" class="btn btn-danger pull-right">
      <span class="glyphicon glyphicon-trash"></span> Clear Database
    </button>
  </form>
  <div style="margin-bottom: 20px;">
    <button type="button" class="btn btn-primary js-upload-photos">
      <span class="glyphicon glyphicon-cloud-upload"></span> Upload files

    </button>


    <input id="fileupload" type="file"  accept=".pdf" name="file" multiple
           style="display: none;"
           data-url="{% url 'marketing:basic_upload' %}"
           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
  </div>
<a href="{% url 'marketing:fun_read_pdf' %}" class="btn btn-primary">Read Pdf</a>
  <table id="gallery" class="table table-bordered">
    <thead>
      <tr>
        <th>Pdfs</th>
      </tr>
    </thead>
    <tbody>
      {% for pdfs in pdf %}
        <tr>
          <td><a href="{{ pdfs.file.url }}">{{ pdfs.file.name }}</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

<script>

</script>
{% endblock %}